/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

console.time('FIBEVEN');
//let bigInt = require("big-integer");
const { fibonacci, isMult } = require('../utils/math_utils'); // my fibonacci functional

const max = 4000000;
let i = 0;
let fbi = fibonacci(i);
let sum = 0;
while (fbi <= max) {
    if(isMult(String(fbi),2)){
        console.log(`${i} = ${fbi}`);
        sum += fbi;
    }
    i++;
    fbi = fibonacci(i);
}
console.log(`suma ${sum}`);
console.timeEnd('FIBEVEN');